### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem-old#10]
We need to provide better documentation. Do we want to do this as a wiki, readthedocs, or a long readme? 

To start we should at least have the following documented:

Overview of the system

How to install
 - Requirements
 - Step-by-step walk through (totem, rabbit, ...)

How to run a tasking
 - format for AMQP message

How to Create a Service

**Comment by webstergd** [comment]
Discuss Java 8

**Comment by zhanif3** [comment]
This issue was moved to HolmesProcessing/Holmes-Totem#10
