### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem-old#11]
We currently only support Java 7. We should add documentation to explain this. We should also discuss if we want to provide support for Java 8 in the future.

**Comment by zhanif3** [comment]
Currently enforced by build.sbt. We can rewrite the buildfile to reflect the usage of 8.

**Comment by zhanif3** [comment]
This issue was moved to HolmesProcessing/Holmes-Totem#11
