### ISSUE TITLE
PEInfo upgrade

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem-old#8]
The current implementation of PEInfo is written with python. This causes potential performance hits when scaling. We should port the code over to GO and leverage the PE library [1]. Looks like all we would need to do is track offsets. 

[1] https://golang.org/pkg/debug/pe/

**Comment by zhanif3** [comment]
Frankly, this is a large alteration. We should consider having a separate repo made to maintain the (effectively) new pefile.

**Comment by zhanif3** [comment]
This issue was moved to HolmesProcessing/Holmes-Totem#8
